true;
false;
null;
123;
123.123;
0X7DE;
asset(2014, 0X7DE, "2014 AND 0X7DE is the same");
0377;
asset(0377, 255, "0377 and 255 is the same!");
"I love to create a JavaScript program!";
'I love to create a JavaScript program!';
'I love to create a \' Javascript program!';
"I love to create a \" Javascript program!";
"I love to create a \\ Javascript program!";
"I love to create a \f Javascript program!";
"I love to create a \b Javascript program!";
"I love to create a \n Javascript program!";
"I love to create a \r Javascript program!";
"I love to create a \t Javascript program!";
"I love to create a \x7DE Javascript program";
"I love to create a \u7DE 7DE 7DE 7DE Javascript program";
"I love to create a \0377 Javascript program";
